### ISSUE TITLE
cr-Cans: use of U+202F as a morpheme separator

### ISSUE THREAD

**Issue by eddieantonio** [w3c/amlreq#4]
ᑖᓂᓯ! I work on making (Western) Cree syllabics more accessible on the web, and I can share my thoughts and experiences with you all. I'm not super sure how to do that, so I'm openning up this issue, and you can pester me about items labelled as "Needs Research".

One somewhat recent innovation in writing Cree syllabics is to use **U+202F NARROW NO-BREAK SPACE** as a morpheme separator.  For example (see: https://crk-orthography.readthedocs.io/en/stable/#:~:text=Hyphens%20in%20Cree%20words).

This mirrors the hyphen's usage in the standard Roman orthography; e.g, ê-wâpamât is ᐁ ᐚᐸᒫᐟ in syllabics.

Why U+202F?

 - it _should_ render as visually thinner than U+0020 — preferablly U+0020 is as wide a full syllabic character, such as ᐃ, and U+202F should render half as wide as U+0020
 - it should NOT be considered a space in word segmentation; indeed, using the [Unicode Standard Annex #29§4.1 Default Word Boundary Specification](https://unicode.org/reports/tr29/#Default_Word_Boundaries), U+202F does not break words. IT also passes the "triple-click test"!
 - precedent set in Mongolian orthography

**Comment by r12a** [comment]
@eddieantonio Apologies for the late response.  Seems i failed to set a watch on this repository, so i have just chanced on your comment now, by accident.  Thanks for the information.  I'll give it some consideration and get back to you.

**Comment by r12a** [comment]
Hello @eddieantonio.  I just came across this issue again.  NNBSP seems to work in all major browsers wrt preventing word breaks, but i noticed that the Noto UCAS fonts don't appear to have a glyph for NNBSP.  I therefore just raised an issue at https://github.com/notofonts/canadian-aboriginal/issues/7. Hope that helps.

**Comment by r12a** [comment]
And the fix is now in place in v2.004 of the Noto UCAS font. See https://typo.social/@webi18n@w3c.social/111929394691370213

@eddieantonio unless there is something else, i propose we close this issue(?)

**Comment by eddieantonio** [comment]
Wonderful news! Yes, absolutely. 🎉
